
import Header from "@/components/headerHome";
import HeaderInnerPage from "@/components/headerInnerPage";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InnerPageLayout({ children }) {
  return (
    <>
    <HeaderInnerPage />
    <main>
        {children}
    </main>
    </>
  );
}
